### ISSUE TITLE
시험 실행시 오류

### ISSUE THREAD

**Issue by EJLEE5826** [CAU-OSS-2019/team-project-team07#11]
구글 colab의 우분투 18.04, 파이썬 3.6 환경에서 실행했습니다.

1. Readme의 How to use의 샘플 실행화면대로 명령어를 입력했지만 시스템상에서 다시 입력을 받았습니다. 둘 중 하나로 통일이 필요합니다.
![1](https://user-images.githubusercontent.com/30209441/58407506-e36cde00-80a6-11e9-854f-cfe50d910f65.PNG)

2. 결과 이미지 저장 위치가 sample_output 폴더 안이어서, 해당 경로가 존재하지 않기 때문에 처음 실행 시 로딩을 다 기다린 후에 한번은 에러메세지를 보게됩니다. 저장 경로를 바꾸어 해결했지만, 수정이 필요합니다.

labels: bug

**Comment by friedcoke** [comment]
1. 에 제시된 이슈의 경우 제작하려는 표에 따른 필요 이미지 갯수가 다르기 때문에 발생 하는 것입니다.
경우에 따라 겹치는 이미지가 필요 할 경우 overlap 이미지를 요청할 수 있습니다. 두 자리 수 인 경우에는 second 이미지, 그리고 overlap second 이미지가 요청 될 수 도 있습니다. README를 좀 더 직관적으로 수정 하겠습니다.
2.에 제시된 이슈는 push과정에서 빠진 문제입니다. 곧 수정 하겠습니다
감사합니다

**Comment by borybory** [comment]
1. README 수정했습니다. develop 브랜치에서 확인 가능합니다. 팀원들과의 협의 후에 master 브랜치에 적용하도록 하겠습니다. 감사합니다.

**Comment by EJLEE5826** [comment]
확인했습니다. 감사합니다.
