### ISSUE TITLE
readme에 있는것 외에도 설치해야 할 항목들이 있습니다.

### ISSUE THREAD

**Issue by h-dyeon** [CAU-OSS-2019/team-project-team07#13]
readme에 적혀있는 대로 설치를 한 후에 colorblindness.py를 실행했지만 오류가 났습니다.
<code>pip install scipy</code>

1. PyQt5가 없어서 설치를 했습니다.
<code>ModuleNotFoundError: No module named 'PyQt5'</code>
<code>pip install PyQt5</code>

2. PIL가 없어서 설치를 했습니다.
<code>ModuleNotFoundError: No module named 'PIL'</code>
<code>pip install image</code>

readme.md 파일에 1번과 2번과 같은 내용도 추가를 하면 좋을것 같습니다.

**Comment by borybory** [comment]
감사합니다. README 수정하겠습니다.
혹시 2번 항목에서 README.md의 사전설치 항목인 pillow를 설치하셨는데도 PIL 오류가 발생하신건가요?? 이 부분도 빠른 시간 내에 확인하겠습니다.

**Comment by h-dyeon** [comment]
아니요 No module named 'PIL'은 1번을 실행하고 나서 마주치게 될 오류라고 생각해서 
미처 설치할 생각을 하지 못했습니다. 지금와서 보니 image대신 pillow를 설치했어야 했네요 감사합니다!

**Comment by borybory** [comment]
GUI를 적용한 README 수정 완료했습니다. 감사합니다.
