### ISSUE TITLE
create 버튼을 다시 눌렀을때 이미지 생성이 되지 않

### ISSUE THREAD

**Issue by h-dyeon** [CAU-OSS-2019/team-project-team07#14]
![08에서7B로 변경했는데 변환이 안됨](https://user-images.githubusercontent.com/31642303/59208340-d8a46400-8be3-11e9-8969-a984e5c94bb9.png)

처음에 <code>python colorblindenss.py</code>를 실행하자마자
first character에는 sample_input/0.png 파일을 넣고
second character에는 sample_input/8.png 파일을 넣었습니다.
오른쪽에 08 이미지가 잘 생성되었습니다.

이후에
first character에는 sample_input/7.png 파일을 넣고
second character에는 sample_input/B.png 파일을 넣었습니다.
그리고 create버튼을 눌렀지만 이미지는 변화가 없었습니다.

![처음부터 7B입력하면 잘 나옴](https://user-images.githubusercontent.com/31642303/59208510-2b7e1b80-8be4-11e9-8aff-1bdeb6c03401.png)
위 사진은 처음부터 7.png와 B.png를 넣었을때 나오는 결과입니다.

이미지를 한번 생성 한 후에 create버튼을 비활성화 시키던지
create버튼을 또 누르면 다른 이미지를 생성할 수 있도록 변경해야 할 것 같습니다.

**Comment by friedcoke** [comment]
이슈 감사 합니다.
최초 이미지 생성 이후 초기화가 제대로 이루어 지지 않는 문제로 확인 생각됩니다. 수정 하겠습니다.

**Comment by friedcoke** [comment]
2자리 수인 경우 이미지 스케일을 조정하여 좌우에 새롭게 배치하게 됩니다. 이 과정을 매번하면 비효율적이기 때문에 최초 한 번만 실행 합니다. 이는 first_flag로 확인하는데 새로운 이미지가 생성시에 first_flag가 갱신 되지 않아 발생하는 문제 였습니다. 수정 완료 했고 정상동작 함을 확인 했습니다.

**Comment by friedcoke** [comment]
추가적으로 반복 실행을 했을 때 이미지 정밀도가 떨어지고 렉이 걸리는 문제를 발견했는데 이는 image를 받아 저장해두는 배열인 images가 초기화 되지 않아서 입니다.  수정 완료했습니다.
