### ISSUE TITLE
주어진 sample input중에 작동하지 않는 input image가 있습니다.

### ISSUE THREAD

**Issue by canis617** [CAU-OSS-2019/team-project-team07#15]
사진 첨부합니다.
![sample+3](https://user-images.githubusercontent.com/38325657/59849390-721d0400-93a2-11e9-9671-58bb0586acee.PNG)
![sample+8](https://user-images.githubusercontent.com/38325657/59849391-721d0400-93a2-11e9-943d-e07877dd0db8.PNG)
![sample+up](https://user-images.githubusercontent.com/38325657/59849392-721d0400-93a2-11e9-8eb2-ebfa0917c01e.PNG)

세 사진 모두 sample_line과 숫자3, 숫자8, line_up을 대입한 사진인데 결과가 똑같습니다!
해당 이슈에 대한 별도의 안내가 없어 이슈 남깁니다.

**Comment by canis617** [comment]
추가적인 정보를 적습니다.
windows10 64bit, python3.7에서 구동하였습니다.

**Comment by friedcoke** [comment]
저희 프로젝트는 한식색각표의 원형을 최대한 유지하고자 했으며 제 1표는 숫자. 문자조합의 2자리 수로 지정 되어 있습니다. 따라서 0_9, A_Z를 넣어야 합니다.
위 샘플에 넣은 sample_line은 제 11표, 제 12표 등 길찾기 에 사용 되는 것이고 sample_up, down은 위 아래로 나뉘어진 길을 찾아 내는 표에 사용 됩니다.
관련 안내 사항을 README에 추가하도록 하겠습니다.

**Comment by canis617** [comment]
![image](https://user-images.githubusercontent.com/38325657/59906695-4e11ff00-9444-11e9-8fdc-7940a2bf0c8a.png)

확인 하였습니다.
11지표, 12지표에서 기능이 정상적으로 작동 함을 확인하였습니다.
확인해 주셔서 감사합니다.
